name: Release
on:
  push:
    branches:
      - main
    paths:
      - 'Dockerfile'
jobs:
  release:
    name: Release
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Run something
        run: |
          echo "Building and publishing"
